[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
base = "light"

[server]
headless = true
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false
